-- EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;

-- ENUMS
CREATE TYPE user_role AS ENUM ('STUDENT', 'TA', 'ADMIN');
CREATE TYPE submission_status AS ENUM ('PENDING', 'SUBMITTED', 'LATE', 'GRADED');
CREATE TYPE risk_level_enum AS ENUM ('WARNING', 'CRITICAL');
CREATE TYPE document_status AS ENUM ('PROCESSING', 'READY');
CREATE TYPE message_sender AS ENUM ('STUDENT', 'AI', 'TA');
CREATE TYPE feedback_enum AS ENUM ('LIKE', 'DISLIKE', 'NEEDS_TA');
CREATE TYPE thread_status AS ENUM ('OPEN', 'RESOLVED');
CREATE TYPE post_author_type AS ENUM ('STUDENT', 'AI', 'TA');
CREATE TYPE verification_status AS ENUM ('UNVERIFIED', 'VERIFIED');
CREATE TYPE chunk_source AS ENUM ('DOCUMENT', 'FORUM_CORRECTION');