# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ai_service_pb2 as ai__service__pb2


class AIThreadServiceStub(object):
    """==========================================
    1. CHAT & THREAD SERVICE
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAIResponse = channel.unary_stream(
                '/ai.teachingassistant.AIThreadService/StreamAIResponse',
                request_serializer=ai__service__pb2.AIRequest.SerializeToString,
                response_deserializer=ai__service__pb2.AIResponse.FromString,
                )
        self.SuggestSimilarThreads = channel.unary_unary(
                '/ai.teachingassistant.AIThreadService/SuggestSimilarThreads',
                request_serializer=ai__service__pb2.SuggestRequest.SerializeToString,
                response_deserializer=ai__service__pb2.SuggestResponse.FromString,
                )
        self.ClassifyIntent = channel.unary_unary(
                '/ai.teachingassistant.AIThreadService/ClassifyIntent',
                request_serializer=ai__service__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=ai__service__pb2.ClassifyResponse.FromString,
                )


class AIThreadServiceServicer(object):
    """==========================================
    1. CHAT & THREAD SERVICE
    ==========================================
    """

    def StreamAIResponse(self, request, context):
        """Luồng Stream AI trả lời
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestSimilarThreads(self, request, context):
        """Luồng gợi ý câu hỏi tương tự (Right Panel UI)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyIntent(self, request, context):
        """Classify user message intent for channel routing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIThreadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAIResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAIResponse,
                    request_deserializer=ai__service__pb2.AIRequest.FromString,
                    response_serializer=ai__service__pb2.AIResponse.SerializeToString,
            ),
            'SuggestSimilarThreads': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestSimilarThreads,
                    request_deserializer=ai__service__pb2.SuggestRequest.FromString,
                    response_serializer=ai__service__pb2.SuggestResponse.SerializeToString,
            ),
            'ClassifyIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyIntent,
                    request_deserializer=ai__service__pb2.ClassifyRequest.FromString,
                    response_serializer=ai__service__pb2.ClassifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.teachingassistant.AIThreadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIThreadService(object):
    """==========================================
    1. CHAT & THREAD SERVICE
    ==========================================
    """

    @staticmethod
    def StreamAIResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ai.teachingassistant.AIThreadService/StreamAIResponse',
            ai__service__pb2.AIRequest.SerializeToString,
            ai__service__pb2.AIResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SuggestSimilarThreads(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.teachingassistant.AIThreadService/SuggestSimilarThreads',
            ai__service__pb2.SuggestRequest.SerializeToString,
            ai__service__pb2.SuggestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClassifyIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.teachingassistant.AIThreadService/ClassifyIntent',
            ai__service__pb2.ClassifyRequest.SerializeToString,
            ai__service__pb2.ClassifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AIDocumentServiceStub(object):
    """==========================================
    3. DOCUMENT SERVICE (TA Upload)
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_unary(
                '/ai.teachingassistant.AIDocumentService/ProcessDocument',
                request_serializer=ai__service__pb2.DocumentRequest.SerializeToString,
                response_deserializer=ai__service__pb2.DocumentResponse.FromString,
                )
        self.UpdateChunkContent = channel.unary_unary(
                '/ai.teachingassistant.AIDocumentService/UpdateChunkContent',
                request_serializer=ai__service__pb2.UpdateChunkRequest.SerializeToString,
                response_deserializer=ai__service__pb2.UpdateChunkResponse.FromString,
                )


class AIDocumentServiceServicer(object):
    """==========================================
    3. DOCUMENT SERVICE (TA Upload)
    ==========================================
    """

    def ProcessDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChunkContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIDocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=ai__service__pb2.DocumentRequest.FromString,
                    response_serializer=ai__service__pb2.DocumentResponse.SerializeToString,
            ),
            'UpdateChunkContent': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChunkContent,
                    request_deserializer=ai__service__pb2.UpdateChunkRequest.FromString,
                    response_serializer=ai__service__pb2.UpdateChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.teachingassistant.AIDocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIDocumentService(object):
    """==========================================
    3. DOCUMENT SERVICE (TA Upload)
    ==========================================
    """

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.teachingassistant.AIDocumentService/ProcessDocument',
            ai__service__pb2.DocumentRequest.SerializeToString,
            ai__service__pb2.DocumentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateChunkContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.teachingassistant.AIDocumentService/UpdateChunkContent',
            ai__service__pb2.UpdateChunkRequest.SerializeToString,
            ai__service__pb2.UpdateChunkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
